
import {
  Code,
  Paintbrush,
  Layers,
  Database,
  Users,
  Palette,
  BrainCircuit,
  Bot,
  BarChart2,
  LineChart,
  Cloud,
  Terminal,
  Smartphone,
  Gamepad2,
  Bitcoin,
  Globe,
  Camera,
  CircuitBoard,
  Shield,
  Server,
  TestTube,
  Plug,
  ToyBrick,
  Lightbulb,
  FileText,
  Python as PythonIcon,
  GitBranch,
  Rocket,
  Atom,
  PenTool,
  Network
} from 'lucide-react';
import { SiJavascript, SiTypescript, SiJava, SiCplusplus, SiGo, SiRust, SiKotlin, SiSwift, SiPhp, SiRuby, SiDart, SiR, SiElixir, SiHaskell, SiGnubash } from 'react-icons/si';
import { FaReact, FaVuejs, FaAngular, FaBootstrap, FaNodeJs, FaPython, FaDocker, FaAws, FaDigitalOcean } from 'react-icons/fa';
import { SiNextdotjs, SiNuxtdotjs, SiSvelte, SiSolid, SiAstro, SiJquery, SiThreedotjs, SiTailwindcss, SiChakraui, SiMui, SiExpress, SiFastify, SiNestjs, SiDjango, SiFlask, SiSpringboot, SiDotnet, SiLaravel, SiRubyonrails, SiAdonisjs, SiPostgresql, SiMysql, SiSqlite, SiMongodb, SiRedis, SiMariadb, SiSupabase, SiPlanetscale, SiVercel, SiNetlify, SiRailway, SiKubernetes, SiTerraform, SiCloudflare, SiTensorflow, SiPytorch, SiScikitlearn, SiHuggingface, SiOpencv, SiLangchain, SiKeras, SiEthereum, SiSolana, SiBinance, SiIonic, SiCapacitor, SiPrisma, SiGraphql, SiMqtt, SiStripe, SiTwilio, SiSendgrid, SiZapier } from 'react-icons/si';


export const roles = [
  { id: 'frontend-developer', label: 'Frontend Developer', icon: <Code size={18} /> },
  { id: 'backend-developer', label: 'Backend Developer', icon: <Server size={18} /> },
  { id: 'full-stack-developer', label: 'Full Stack Developer', icon: <Layers size={18} /> },
  { id: 'database-engineer', label: 'Database Engineer', icon: <Database size={18} /> },
  { id: 'ui-ux-designer', label: 'UI/UX Designer', icon: <Paintbrush size={18} /> },
  { id: 'product-designer', label: 'Product Designer', icon: <PenTool size={18} /> },
  { id: 'machine-learning-engineer', label: 'ML Engineer', icon: <BrainCircuit size={18} /> },
  { id: 'ai-engineer', label: 'AI Engineer', icon: <Bot size={18} /> },
  { id: 'data-scientist', label: 'Data Scientist', icon: <BarChart2 size={18} /> },
  { id: 'data-analyst', label: 'Data Analyst', icon: <LineChart size={18} /> },
  { id: 'devops-engineer', label: 'DevOps Engineer', icon: <Rocket size={18} /> },
  { id: 'mobile-app-developer', label: 'Mobile App Developer', icon: <Smartphone size={18} /> },
  { id: 'game-developer', label: 'Game Developer', icon: <Gamepad2 size={18} /> },
  { id: 'blockchain-developer', label: 'Blockchain Developer', icon: <Bitcoin size={18} /> },
  { id: 'smart-contract-developer', label: 'Smart Contract Dev', icon: <FileText size={18} /> },
  { id: 'ar-vr-developer', label: 'AR/VR Developer', icon: <Camera size={18} /> },
  { id: 'embedded-systems-developer', label: 'Embedded Systems Dev', icon: <CircuitBoard size={18} /> },
  { id: 'cybersecurity-specialist', label: 'Cybersecurity Specialist', icon: <Shield size={18} /> },
  { id: 'cloud-engineer', label: 'Cloud Engineer', icon: <Cloud size={18} /> },
  { id: 'qa-engineer-tester', label: 'QA Engineer / Tester', icon: <TestTube size={18} /> },
  { id: 'api-integration-specialist', label: 'API Integration Specialist', icon: <Plug size={18} /> },
  { id: 'hardware-engineer', label: 'Hardware Engineer', icon: <ToyBrick size={18} /> },
  { id: 'iot-developer', label: 'IoT Developer', icon: <Network size={18} /> },
  { id: 'researcher', label: 'Researcher', icon: <Lightbulb size={18} /> },
  { id: 'project-manager', label: 'Project Manager', icon: <Users size={18} /> },
  { id: 'technical-writer', label: 'Technical Writer', icon: <FileText size={18} /> },
];


const iconProps = { size: 18, className: 'text-muted-foreground' };

export const technologies = [
  // Languages
  { id: 'python', label: 'Python', icon: <FaPython {...iconProps} /> },
  { id: 'javascript', label: 'JavaScript', icon: <SiJavascript {...iconProps} /> },
  { id: 'typescript', label: 'TypeScript', icon: <SiTypescript {...iconProps} /> },
  { id: 'java', label: 'Java', icon: <FaJava {...iconProps} /> },
  { id: 'c', label: 'C', icon: <span className="font-bold text-muted-foreground">C</span> },
  { id: 'c++', label: 'C++', icon: <SiCplusplus {...iconProps} /> },
  { id: 'c#', label: 'C#', icon: <span className="font-bold text-muted-foreground">C#</span> },
  { id: 'go', label: 'Go', icon: <SiGo {...iconProps} /> },
  { id: 'rust', label: 'Rust', icon: <SiRust {...iconProps} /> },
  { id: 'kotlin', label: 'Kotlin', icon: <SiKotlin {...iconProps} /> },
  { id: 'swift', label: 'Swift', icon: <SiSwift {...iconProps} /> },
  { id: 'php', label: 'PHP', icon: <SiPhp {...iconProps} /> },
  { id: 'ruby', label: 'Ruby', icon: <SiRuby {...iconProps} /> },
  { id: 'dart', label: 'Dart', icon: <SiDart {...iconProps} /> },
  { id: 'r', label: 'R', icon: <SiR {...iconProps} /> },
  { id: 'matlab', label: 'MATLAB', icon: <span className="font-bold text-muted-foreground">M</span> },
  { id: 'scala', label: 'Scala', icon: <span className="font-bold text-muted-foreground">S</span> },
  { id: 'elixir', label: 'Elixir', icon: <SiElixir {...iconProps} /> },
  { id: 'haskell', label: 'Haskell', icon: <SiHaskell {...iconProps} /> },
  { id: 'bash/shell', label: 'Bash/Shell', icon: <SiGnubash {...iconProps} /> },

  // Frontend
  { id: 'react', label: 'React', icon: <FaReact {...iconProps} /> },
  { id: 'next.js', label: 'Next.js', icon: <SiNextdotjs {...iconProps} /> },
  { id: 'vue.js', label: 'Vue.js', icon: <FaVuejs {...iconProps} /> },
  { id: 'nuxt.js', label: 'Nuxt.js', icon: <SiNuxtdotjs {...iconProps} /> },
  { id: 'angular', label: 'Angular', icon: <FaAngular {...iconProps} /> },
  { id: 'svelte', label: 'Svelte', icon: <SiSvelte {...iconProps} /> },
  { id: 'solidjs', label: 'SolidJS', icon: <SiSolid {...iconProps} /> },
  { id: 'astro', label: 'Astro', icon: <SiAstro {...iconProps} /> },
  { id: 'jquery', label: 'jQuery', icon: <SiJquery {...iconProps} /> },
  { id: 'three.js', label: 'Three.js', icon: <SiThreedotjs {...iconProps} /> },
  { id: 'tailwind-css', label: 'Tailwind CSS', icon: <SiTailwindcss {...iconProps} /> },
  { id: 'shadcn/ui', label: 'shadcn/ui', icon: <span className="font-bold text-muted-foreground">S/</span> },
  { id: 'bootstrap', label: 'Bootstrap', icon: <FaBootstrap {...iconProps} /> },
  { id: 'chakra-ui', label: 'Chakra UI', icon: <SiChakraui {...iconProps} /> },
  { id: 'material-ui', label: 'Material UI', icon: <SiMui {...iconProps} /> },

  // Backend
  { id: 'node.js', label: 'Node.js', icon: <FaNodeJs {...iconProps} /> },
  { id: 'express.js', label: 'Express.js', icon: <SiExpress {...iconProps} /> },
  { id: 'fastify', label: 'Fastify', icon: <SiFastify {...iconProps} /> },
  { id: 'nestjs', label: 'NestJS', icon: <SiNestjs {...iconProps} /> },
  { id: 'django', label: 'Django', icon: <SiDjango {...iconProps} /> },
  { id: 'flask', label: 'Flask', icon: <SiFlask {...iconProps} /> },
  { id: 'spring-boot', label: 'Spring Boot', icon: <SiSpringboot {...iconProps} /> },
  { id: 'asp.net-core', label: 'ASP.NET Core', icon: <SiDotnet {...iconProps} /> },
  { id: 'laravel', label: 'Laravel', icon: <SiLaravel {...iconProps} /> },
  { id: 'ruby-on-rails', label: 'Ruby on Rails', icon: <SiRubyonrails {...iconProps} /> },
  { id: 'adonisjs', label: 'AdonisJS', icon: <SiAdonisjs {...iconProps} /> },
  { id: 'fiber-(go)', label: 'Fiber (Go)', icon: <SiGo {...iconProps} /> },
  { id: 'phoenix-(elixir)', label: 'Phoenix (Elixir)', icon: <SiElixir {...iconProps} /> },

  // Database
  { id: 'mysql', label: 'MySQL', icon: <SiMysql {...iconProps} /> },
  { id: 'postgresql', label: 'PostgreSQL', icon: <SiPostgresql {...iconProps} /> },
  { id: 'sqlite', label: 'SQLite', icon: <SiSqlite {...iconProps} /> },
  { id: 'mongodb', label: 'MongoDB', icon: <SiMongodb {...iconProps} /> },
  { id: 'firebase-realtime-db', label: 'Firebase Realtime DB', icon: <Atom {...iconProps} /> },
  { id: 'firestore', label: 'Firestore', icon: <Atom {...iconProps} /> },
  { id: 'redis', label: 'Redis', icon: <SiRedis {...iconProps} /> },
  { id: 'cassandra', label: 'Cassandra', icon: <Database {...iconProps} /> },
  { id: 'neo4j', label: 'Neo4j', icon: <SiMongodb {...iconProps} /> },
  { id: 'mariadb', label: 'MariaDB', icon: <SiMariadb {...iconProps} /> },
  { id: 'supabase', label: 'Supabase', icon: <SiSupabase {...iconProps} /> },
  { id: 'planetscale', label: 'PlanetScale', icon: <SiPlanetscale {...iconProps} /> },

  // DevOps/Cloud
  { id: 'aws', label: 'AWS', icon: <FaAws {...iconProps} /> },
  { id: 'azure', label: 'Azure', icon: <Cloud {...iconProps} /> },
  { id: 'google-cloud-platform', label: 'Google Cloud Platform', icon: <Cloud {...iconProps} /> },
  { id: 'vercel', label: 'Vercel', icon: <SiVercel {...iconProps} /> },
  { id: 'netlify', label: 'Netlify', icon: <SiNetlify {...iconProps} /> },
  { id: 'railway', label: 'Railway', icon: <SiRailway {...iconProps} /> },
  { id: 'docker', label: 'Docker', icon: <FaDocker {...iconProps} /> },
  { id: 'kubernetes', label: 'Kubernetes', icon: <SiKubernetes {...iconProps} /> },
  { id: 'terraform', label: 'Terraform', icon: <SiTerraform {...iconProps} /> },
  { id: 'digitalocean', label: 'DigitalOcean', icon: <FaDigitalOcean {...iconProps} /> },
  { id: 'cloudflare', label: 'Cloudflare', icon: <SiCloudflare {...iconProps} /> },

  // AI/ML
  { id: 'tensorflow', label: 'TensorFlow', icon: <SiTensorflow {...iconProps} /> },
  { id: 'pytorch', label: 'PyTorch', icon: <SiPytorch {...iconProps} /> },
  { id: 'scikit-learn', label: 'Scikit-learn', icon: <SiScikitlearn {...iconProps} /> },
  { id: 'hugging-face', label: 'Hugging Face', icon: <SiHuggingface {...iconProps} /> },
  { id: 'opencv', label: 'OpenCV', icon: <SiOpencv {...iconProps} /> },
  { id: 'langchain', label: 'LangChain', icon: <SiLangchain {...iconProps} /> },
  { id: 'keras', label: 'Keras', icon: <SiKeras {...iconProps} /> },

  // Blockchain
  { id: 'ethereum', label: 'Ethereum', icon: <SiEthereum {...iconProps} /> },
  { id: 'polygon', label: 'Polygon', icon: <SiEthereum {...iconProps} /> },
  { id: 'solana', label: 'Solana', icon: <SiSolana {...iconProps} /> },
  { id: 'avalanche', label: 'Avalanche', icon: <Bitcoin {...iconProps} /> },
  { id: 'binance-smart-chain', label: 'Binance Smart Chain', icon: <SiBinance {...iconProps} /> },
  { id: 'hardhat', label: 'Hardhat', icon: <Bitcoin {...iconProps} /> },
  { id: 'truffle', label: 'Truffle', icon: <Bitcoin {...iconProps} /> },
  { id: 'web3.js', label: 'Web3.js', icon: <SiJavascript {...iconProps} /> },
  { id: 'ethers.js', label: 'Ethers.js', icon: <SiJavascript {...iconProps} /> },

  // Mobile
  { id: 'react-native', label: 'React Native', icon: <FaReact {...iconProps} /> },
  { id: 'flutter', label: 'Flutter', icon: <SiTypescript {...iconProps} /> },
  { id: 'swift-(ios)', label: 'Swift (iOS)', icon: <SiSwift {...iconProps} /> },
  { id: 'kotlin-(android)', label: 'Kotlin (Android)', icon: <SiKotlin {...iconProps} /> },
  { id: 'ionic', label: 'Ionic', icon: <SiIonic {...iconProps} /> },
  { id: 'capacitor', label: 'Capacitor', icon: <SiCapacitor {...iconProps} /> },
  { id: 'xamarin', label: 'Xamarin', icon: <Smartphone {...iconProps} /> },

  // Other
  { id: 'prisma', label: 'Prisma', icon: <SiPrisma {...iconProps} /> },
  { id: 'graphql', label: 'GraphQL', icon: <SiGraphql {...iconProps} /> },
  { id: 'rest-apis', label: 'REST APIs', icon: <Plug {...iconProps} /> },
  { id: 'grpc', label: 'gRPC', icon: <Server {...iconProps} /> },
  { id: 'mqtt', label: 'MQTT', icon: <SiMqtt {...iconProps} /> },
  { id: 'websockets', label: 'WebSockets', icon: <GitBranch {...iconProps} /> },
  { id: 'stripe-api', label: 'Stripe API', icon: <SiStripe {...iconProps} /> },
  { id: 'twilio-api', label: 'Twilio API', icon: <SiTwilio {...iconProps} /> },
  { id: 'sendgrid', label: 'SendGrid', icon: <SiSendgrid {...iconProps} /> },
  { id: 'zapier', label: 'Zapier', icon: <SiZapier {...iconProps} /> },
];

export const skills = [
  ...roles.map(r => ({id: r.id, label: r.label})),
  ...technologies.map(t => ({id: t.id, label: t.label})),
];
