
import type { UserProfile, Event, Notification } from './db';

export const dummyUsers: UserProfile[] = [
  {
    uid: 'user-001-dev',
    fullName: 'Alex Doe',
    email: 'alex.doe@example.com',
    photoURL: 'https://i.pravatar.cc/150?u=alexdoe',
    role: 'participant',
    age: 24,
    city: 'San Francisco, CA',
    techStack: ['React', 'Next.js', 'TypeScript', 'Node.js', 'Tailwind CSS', 'Firebase'],
    skills: ['Frontend Development', 'UI/UX Design', 'Full Stack Developer', 'Product Management'],
    pastHackathons: 'Won "Best Social Impact" at Hack The Bay 2023. Participated in 5 other hackathons.',
    pastProjects: 'Developed a real-time collaborative code editor. Created a mobile app for local event discovery.',
    socials: {
        github: 'https://github.com/alexdoe',
        linkedin: 'https://linkedin.com/in/alexdoe',
    },
    followers: 125,
    following: 78,
    connections: ['user-002-dev', 'user-003-dev', 'user-004-dev'],
  },
  {
    uid: 'user-002-dev',
    fullName: 'Ben Smith',
    email: 'ben.s@example.com',
    photoURL: 'https://i.pravatar.cc/150?u=bensmith',
    role: 'participant',
    age: 28,
    city: 'New York, NY',
    techStack: ['Python', 'Django', 'PostgreSQL', 'Docker', 'AWS'],
    skills: ['Backend Development', 'DevOps', 'Data Science'],
    pastHackathons: 'Finalist at AI Global Hackathon 2023.',
    pastProjects: 'Built a predictive analytics model for e-commerce sales.',
    socials: {
        github: 'https://github.com/bensmith',
        linkedin: 'https://linkedin.com/in/bensmith',
    },
    followers: 210,
    following: 150,
    connections: ['user-001-dev', 'user-004-dev'],
  },
   {
    uid: 'user-003-dev',
    fullName: 'Chloe Garcia',
    email: 'chloe.g@example.com',
    photoURL: 'https://i.pravatar.cc/150?u=chloegarcia',
    role: 'participant',
    age: 22,
    city: 'Austin, TX',
    techStack: ['Figma', 'Adobe XD', 'UserTesting', 'HTML/CSS'],
    skills: ['UI/UX Design', 'User Research', 'Prototyping'],
    pastHackathons: 'Best Design award at Creatives Con 2024.',
    pastProjects: 'Redesigned the mobile app for a local non-profit.',
    socials: {
        github: 'https://github.com/chloegarcia',
        linkedin: 'https://linkedin.com/in/chloegarcia',
    },
    followers: 300,
    following: 200,
    connections: ['user-001-dev', 'user-005-dev'],
  },
   {
    uid: 'user-004-dev',
    fullName: 'David Kim',
    email: 'david.k@example.com',
    photoURL: 'https://i.pravatar.cc/150?u=davidkim',
    role: 'organizer',
    age: 31,
    city: 'Seattle, WA',
    techStack: ['Project Management', 'Marketing', 'Community Building'],
    skills: ['Event Organization', 'Public Speaking'],
    pastHackathons: 'Organized Seattle Hacks 2022 and 2023.',
    socials: {
        linkedin: 'https://linkedin.com/in/davidkim',
    },
    followers: 500,
    following: 50,
  },
   {
    uid: 'user-005-dev',
    fullName: 'Emily White',
    email: 'emily.w@example.com',
    photoURL: 'https://i.pravatar.cc/150?u=emilywhite',
    role: 'participant',
    age: 26,
    city: 'Chicago, IL',
    techStack: ['Solidity', 'Hardhat', 'ethers.js', 'The Graph'],
    skills: ['Blockchain Development', 'Smart Contracts', 'dApp Development'],
    pastHackathons: 'Won the Web3 track at ETHDenver 2024.',
    pastProjects: 'Launched an NFT marketplace on Polygon.',
    socials: {
        github: 'https://github.com/emilywhite',
    },
    followers: 180,
    following: 95,
    connections: ['user-003-dev'],
  },
];

export const dummyEvents: Event[] = [
    {
        id: 'AIGH24',
        name: 'AI Global Hackathon 2024',
        description: 'A global hackathon focused on pushing the boundaries of Artificial Intelligence. Participants will work in teams to develop innovative AI-powered solutions to real-world problems. The event will feature workshops from industry experts, mentorship sessions, and a final presentation to a panel of judges.',
        dateRange: { from: '2024-10-26T09:00:00Z', to: '2024-10-27T17:00:00Z' },
        techStack: ['Python', 'TensorFlow', 'PyTorch', 'Next.js', 'LangChain', 'Docker', 'GCP'],
        requiredSkills: ['Machine Learning', 'Frontend Development', 'UI/UX Design', 'Backend Development', 'Data Science'],
        maxTeamSize: 5,
        organizerId: 'user-004-dev',
        participants: ['user-001-dev', 'user-002-dev', 'user-004-dev'],
        imageUrl: 'https://placehold.co/600x400.png?text=AI+Global+Hackathon',
    },
    {
        id: 'WEB3CN',
        name: 'Web3 Con & Hackathon',
        description: 'Build the future of the decentralized web. Workshops, talks, and a massive hackathon for developers, designers, and visionaries in the blockchain space.',
        dateRange: { from: '2024-11-15T10:00:00Z', to: '2024-11-17T18:00:00Z' },
        techStack: ['Solidity', 'React', 'ethers.js', 'IPFS', 'The Graph'],
        requiredSkills: ['Blockchain', 'Smart Contracts', 'dApp Development'],
        maxTeamSize: 4,
        organizerId: 'user-004-dev',
        participants: ['user-003-dev', 'user-005-dev', 'user-004-dev'],
        imageUrl: 'https://placehold.co/600x400.png?text=Web3+Con',
    },
    {
        id: 'GAME25',
        name: 'Global Game Jam 2025',
        description: 'Create a video game from scratch in 48 hours. Join thousands of developers, artists, and designers worldwide in this celebration of creativity and game development.',
        dateRange: { from: '2025-01-24T17:00:00Z', to: '2025-01-26T17:00:00Z' },
        techStack: ['Unity', 'C#', 'Blender', 'Godot', 'Unreal Engine'],
        requiredSkills: ['Game Design', '3D Modeling', 'C# Programming', 'Pixel Art'],
        maxTeamSize: 6,
        organizerId: 'user-004-dev',
        participants: ['user-001-dev', 'user-002-dev', 'user-003-dev', 'user-005-dev', 'user-004-dev'],
        imageUrl: 'https://placehold.co/600x400.png?text=Global+Game+Jam',
    },
];


export const dummyNotifications: Omit<Notification, 'status' | 'createdAt'>[] = [
    {
        recipientId: 'user-001-dev',
        senderId: 'user-002-dev',
        senderName: 'Ben Smith',
        type: 'CONNECTION_REQUEST',
        message: 'Ben Smith wants to connect with you.',
    },
    {
        recipientId: 'user-001-dev',
        senderId: 'user-003-dev',
        senderName: 'Chloe Garcia',
        type: 'TEAM_INVITE',
        message: 'Chloe Garcia invited you to join "Design Dynamos" for the AI Global Hackathon.',
        projectIdea: 'An app to help designers find color palettes.',
        role: 'Frontend Developer',
    }
];
